Feature 109 (rewrite of the featurization code )
HoloClean/HoloClean-Legacy-deprecated pull request #114
Opened 2018-03-16 05:35 UTC by gmichalo

2018-03-16 19:57 UTC, j48zheng requested changes

2018-03-16 19:57 UTC, j48zheng commented on holoclean/featurization/Cooccurrancefeaturizer.py
> +        :param  table_name: the name of the table that we need to check the attributes
Typo in function name,
Also please give an example output. Unclear exactly what function does.

2018-03-16 19:58 UTC, ah89 commented
get_dc_attributes in parser_interface still vague to me.

2018-03-16 20:11 UTC, JVonderwell requested changes

2018-03-16 20:11 UTC, JVonderwell commented on holoclean/errordetection/mysql_dcerrordetector.py
> +                componets = predicate.split(operation)
typo in components

2018-03-16 20:11 UTC, JVonderwell commented on holoclean/errordetection/mysql_dcerrordetector.py
> +                    if component.find("table1.") == -1 and component.find("table2.") == -1:
pep8 - 80 chars per line. there's a lot of these.

2018-03-16 20:11 UTC, JVonderwell commented on holoclean/errordetection/mysql_dcerrordetector.py
>          :param dataset: list od dataset names
typo: od should be of

2018-03-16 20:11 UTC, JVonderwell commented on holoclean/featurization/Cooccurrancefeaturizer.py
> +from featurizer import Featurizer
coccurence is misspelled in the file name. I'm nitpicking on purpose with this stuff BTW.

2018-03-16 20:11 UTC, JVonderwell commented on holoclean/featurization/Cooccurrancefeaturizer.py
> +from featurizer import Featurizer
also, pick camelcase or underscores for file names. I don't know what that's supposed to be. pick a convention and stick to it.

2018-03-16 20:11 UTC, JVonderwell commented on holoclean/featurization/Cooccurrancefeaturizer.py
> +        self.attr_costrained = attr_constrained
typo in self.attr_constrained.

2018-03-16 20:11 UTC, JVonderwell commented on holoclean/featurization/Initfeaturizer.py
> +        self.attr_costrained = attr_constrained
typo in self.attr_constrained.

2018-03-16 20:11 UTC, JVonderwell commented on holoclean/holoclean.py
> +from utils.parser_interface import ParserInterface
we should never be merging feature branches like here. especially when they're under review and still in-development. makes reviewing and merging branches much more difficult. in the future, if we need tools from another feature please wait until it's complete and merged into dev.

2018-03-16 20:11 UTC, JVonderwell commented on holoclean/holoclean.py
> +from utils.parser_interface import ParserInterface
I'll leave comments on the interface itself on the other pull request since Theo already started there.

2018-03-16 20:26 UTC, ah89 commented
get_all_constraint_attributes seems redundant, it just instantiation and calling a method

2018-03-16 20:35 UTC, thodrek requested changes
For now....

2018-03-16 20:35 UTC, thodrek commented on holoclean/errordetection/abstract_errordetector.py
> +class Abstract_Error_Detection:
shorten the name. Abstract is not needed. Also Class names do not contain '_'.

2018-03-16 20:35 UTC, thodrek commented on holoclean/errordetection/dcerrordetector.py
> +
Why spaces?

2018-03-16 20:35 UTC, thodrek commented on holoclean/errordetection/mysql_dcerrordetector.py
> +        operationsarr = ['=', '<>', '<=', '>=', '<', '>']
why are operations defined again here. We define them once somewhere as Global params and that's it.

2018-03-16 20:35 UTC, thodrek commented on holoclean/errordetection/mysql_dcerrordetector.py
> +                componets = predicate.split(operation)
components.

2018-03-16 20:35 UTC, thodrek commented on holoclean/errordetection/mysql_dcerrordetector.py
> +            tables = ["table1", "table2"]
what are these hardcoded tables??

2018-03-16 20:35 UTC, thodrek commented on holoclean/errordetection/mysql_dcerrordetector.py
> +                        self.dataset.table_specific_name("Init") + " as  table2 " + \
fix space before as

2018-03-16 20:35 UTC, thodrek commented on holoclean/featurization/Cooccurrancefeaturizer.py
> +    def _get_constraint_attibute(self, table_name, attr_column_name):
What on earth is this doing here???? Why are there constraints in cooccur?

2018-03-16 20:35 UTC, thodrek commented on holoclean/featurization/Cooccurrancefeaturizer.py
> +        specific_features = "("
create the thing first and then wrap it in "(" and ")" what on earth is this?

2018-03-16 20:35 UTC, thodrek commented on holoclean/featurization/Initfeaturizer.py
> +    def _get_constraint_attibute(self, table_name, attr_column_name):
What is this again? Why is there the word DC in Init???????

2018-03-16 20:44 UTC, ah89 commented
typo in name_atttribute

2018-03-16 21:34 UTC, ah89 commented
58-86 in DCfeaturizer are clearer, but still has 3 nested loops, there is another solution that based on the string matching which needs fewer loops.

2018-03-16 22:01 UTC, j48zheng approved these changes

2018-03-16 22:02 UTC, ah89 commented
In the DCFeaturizer , creating_table_name can change to static method

2018-03-16 22:04 UTC, ah89 commented
_create_all_relaxed_dc in DCFeaturizer there is nested loop with same name parameter

2018-03-16 22:05 UTC, gmichalo commented on holoclean/errordetection/dcerrordetector.py
> +
We have spaces between the description, the parameter and the results because this is used to create automatically the docs in readthedocs.org for holoclean

2018-03-16 22:07 UTC, ah89 commented
In line 95 of DCFeaturizer there is input is not mentioned in the arguments

2018-03-16 22:08 UTC, j48zheng requested changes

2018-03-16 22:08 UTC, j48zheng commented on holoclean/featurization/dcfeaturizer.py
> +    def creating_table_name(self, name):
This is only used in _create_relaxed_dc's. Make it private or a static method.

2018-03-16 22:13 UTC, ah89 commented
In parser_interface,line 155 , type term used which is a built-in name so dot use that

2018-03-16 22:14 UTC, gmichalo commented on holoclean/featurization/dcfeaturizer.py
> +    def creating_table_name(self, name):
it is fixed

2018-03-16 22:22 UTC, gmichalo commented on holoclean/errordetection/mysql_dcerrordetector.py
> +            tables = ["table1", "table2"]
In the current dcparcer we can only have table1 and table2. This list help us iterate over the same query twice by selecting first table1.index and in the second time table2.index, so we will not lose any dk cells

2018-03-16 22:27 UTC, ah89 commented
in line 20 , spark_session introduced which is not an argument  for __init__

2018-03-16 22:30 UTC, ah89 commented
in line 118, self.possible_table_name = self.dataset.table_specific_name(name) can be removed because it seems it is not object class property , because you cannot have it without calling get_query method

2018-03-16 22:59 UTC, j48zheng submitted a review, later dismissed

2018-03-16 23:07 UTC, ah89 submitted a review, later dismissed

2018-03-16 23:12 UTC, j48zheng submitted a review, later dismissed

2018-03-16 23:29 UTC, JVonderwell requested changes

2018-03-16 23:29 UTC, JVonderwell commented on holoclean/errordetection/dcerrordetector.py
> +    This class is a subclass of the abstract_errodetector class and
small typo - abstract_errordetector

2018-03-16 23:29 UTC, JVonderwell commented on holoclean/errordetection/dcerrordetector.py
>          :param dataset: list od dataset names
typo - od should be of

2018-03-16 23:29 UTC, JVonderwell commented on holoclean/errordetection/mysql_dcerrordetector.py
> +    This class is a subclass of the abstract_errodetector class and
typo - abstract_errodetector

2018-03-16 23:29 UTC, JVonderwell commented on holoclean/errordetection/mysql_dcerrordetector.py
> +                    if component.find("table1.") == -1 and \
simply this condition to, if component.find("table1." != -1 or component.find("table2.") != -1: then do attribute stuff. This way it's more clear when we actualy do the work and eliminates the need for an else clause.

2018-03-16 23:29 UTC, JVonderwell commented on holoclean/errordetection/mysql_dcerrordetector.py
>          This method finds the predicates of dc"
why quotes at the end?

2018-03-16 23:29 UTC, JVonderwell commented on holoclean/errordetection/mysql_dcerrordetector.py
>          :param cond: a denial constrain
typo - constraint

2018-03-16 23:29 UTC, JVonderwell commented on holoclean/errordetection/mysql_dcerrordetector.py
>          :rtype: list_preds: list of predicates
we use return everywhere else. why rtype here?

2018-03-16 23:29 UTC, JVonderwell commented on holoclean/errordetection/mysql_dcerrordetector.py
> +            tables = ["table1", "table2"]
I would make sure to comment something like what you wrote there if we're going to hardcode it. Not very clear to me that they relate to the denial constraints since I'm fairly unfamilar with the code.

2018-03-16 23:29 UTC, JVonderwell commented on holoclean/featurization/cooccurrencefeaturizer.py
> +    will return the mysql query which represent the Initial Signal for
pretty sure you mean Cooccur signal, not Initial.

2018-03-16 23:29 UTC, JVonderwell commented on holoclean/featurization/cooccurrencefeaturizer.py
> +        :param attr_constrained: list of atttributes that are part of a dc
small typo - attributes has one too many t's

2018-03-16 23:29 UTC, JVonderwell commented on holoclean/featurization/cooccurrencefeaturizer.py
> +        example_output : "(cooccur.attr_first = 'City' OR
I like the example output you included here. Helps just to get a quick idea of what we will be looking at. More of these would be great!

2018-03-16 23:29 UTC, JVonderwell commented on holoclean/featurization/cooccurrencefeaturizer.py
> +        OR cooccur.attr_first = 'ZipCode' OR cooccur.attr_first = 'State'
nitpick - just looks weird that you see 2 Or conditions on the same line when the rest are not. consistent formatting please!

2018-03-16 23:29 UTC, JVonderwell commented on holoclean/featurization/dcfeaturizer.py
> +        This method creates a list of all the possible relaxed DC's
an example of what a relaxed DC looks like would help. I know what you're talking about, but someone unfamiliar with the project might not.

2018-03-16 23:29 UTC, JVonderwell commented on holoclean/featurization/dcfeaturizer.py
> +        This method choose the appropriate name of the table for the query
super nitpick - choose should be chooses

2018-03-16 23:29 UTC, JVonderwell commented on holoclean/featurization/dcfeaturizer.py
> +    def _creating_table_name(self, name):
this function name doesn't really represent what we're doing. _comparison_table_name maybe? something to do with the table we're comparing too.

2018-03-16 23:29 UTC, JVonderwell commented on holoclean/featurization/initfeaturizer.py
> +        OR cooccur.attr_first = 'ZipCode' OR cooccur.attr_first = 'State'
again, the two ORs on one line just looks goofy.

2018-03-16 23:29 UTC, JVonderwell commented on holoclean/utils/reader.py
> +    """TODO:Reader class:Finds the extesion of the file and calls the
typo - extension

2018-03-16 23:29 UTC, JVonderwell commented on holoclean/utils/reader.py
> +    """TODO:Reader class:Finds the extesion of the file and calls the
also get rid of TODO if it's done. that applies to __init__ as well.

2018-03-16 23:42 UTC, ah89 submitted a review, later dismissed

2018-03-16 23:42 UTC, JVonderwell commented on holoclean/utils/pruning.py
pep8 this file. like 20 lines with more than 80 chars and one blank line.

2018-03-16 23:46 UTC, j48zheng submitted a review, later dismissed

2018-03-17 00:35 UTC, j48zheng submitted a review, later dismissed

2018-03-17 00:39 UTC, gmichalo commented on holoclean/errordetection/mysql_dcerrordetector.py
> +                    if component.find("table1.") == -1 and \
I think this will not work. Because this condition needs to check if we do not find neither table1 and table2. But with the "or" we may have table1 and not table2 so this condition will be correct but we may not have neither table1 and table2 so it again be true

2018-03-17 01:46 UTC, gmichalo commented on holoclean/featurization/dcfeaturizer.py
> +        This method creates a list of all the possible relaxed DC's
I added an example after the description of the method

2018-03-17 01:50 UTC, gmichalo commented on holoclean/utils/pruning.py
now pruning.py passes pep8

2018-03-17 02:09 UTC, JVonderwell submitted a review, later dismissed

2018-03-17 02:47 UTC, ah89 submitted a review, later dismissed

2018-03-17 03:35 UTC, j48zheng submitted a review, later dismissed

2018-03-17 03:42 UTC, j48zheng submitted a review, later dismissed

2018-03-17 03:44 UTC, ah89 submitted a review, later dismissed

2018-03-17 03:49 UTC, j48zheng submitted a review, later dismissed

2018-03-17 03:51 UTC, ah89 submitted a review, later dismissed

2018-03-17 14:44 UTC, thodrek requested changes

2018-03-17 14:44 UTC, thodrek commented on holoclean/errordetection/mysql_dcerrordetector.py
> +        self.operationsarr = ['=', '<>', '<=', '>=', '<', '>']
I asked before why these are redefined here!?

2018-03-17 14:44 UTC, thodrek commented on holoclean/errordetection/mysql_dcerrordetector.py
> +        self.table_names = ["table1", "table2"]
What are these two names?

2018-03-17 14:44 UTC, thodrek commented on holoclean/featurization/cooccurrencefeaturizer.py
> +        are part of a DC violation
Why on earth is the phrase DC violation in co-occur?

2018-03-17 14:44 UTC, thodrek commented on holoclean/featurization/cooccurrencefeaturizer.py
> +        OR cooccur.attr_first = 'Stateavg'
This is a bad example. You never mention it refers to hospital and you don't have a schema here. Simply remove.

2018-03-17 14:44 UTC, thodrek commented on holoclean/featurization/cooccurrencefeaturizer.py
> +            init_flat = "Init_flat_join"
Last time I saw the phrase "flat join" you had materialized a full crossproduct. Make sure that you don't do anything like that...

2018-03-17 14:44 UTC, thodrek commented on holoclean/featurization/dcfeaturizer.py
> +        This method creates a list of all the possible relaxed DC's
These examples should be self-contained and they are not. Fix them.

2018-03-17 14:44 UTC, thodrek commented on holoclean/featurization/dcfeaturizer.py
> +            if predicate_type == 0:
What are the predicate types? Whoever is going to touch this code again has no clue what these are.

2018-03-17 14:44 UTC, thodrek commented on holoclean/featurization/dcfeaturizer.py
> +                raise ValueError('predicate type can only be 0, 1 or 2')
Extremely non-informative error message. What is 0, 1 or 2. Why not 42?

2018-03-17 14:44 UTC, thodrek commented on holoclean/featurization/initfeaturizer.py
> +        are part of a DC violation
Stop copying and pasting blindly!!!

2018-03-17 19:14 UTC, j48zheng approved these changes

2018-03-17 22:36 UTC, thodrek approved these changes

2018-03-17 22:42 UTC, merged