The cleaned codes for dataengine and dataset
HoloClean/HoloClean-Legacy-deprecated pull request #124
Opened 2018-03-17 05:25 UTC by ah89

Please Review this code and leave comments

2018-03-17 23:23 UTC, j48zheng submitted a review, later dismissed

2018-03-17 23:29 UTC, j48zheng submitted a review, later dismissed

2018-03-17 23:57 UTC, thodrek submitted a review, later dismissed
Looks good to me just fix that typo.

2018-03-17 23:57 UTC, thodrek commented on holoclean/dataset.py
> +        This method writes dataset id inside dataset_id.txt file and return that
returns that id.

2018-03-18 01:33 UTC, JVonderwell requested changes

2018-03-18 01:33 UTC, JVonderwell commented on holoclean/dataengine.py
> +        This method gets table general name and returns a spark dataframe
typo - dataframe that contains

2018-03-18 01:33 UTC, JVonderwell commented on holoclean/dataengine.py
> +        :param dataset: The data set object to access to the correct project
typo - 'access the' not 'access to the'

2018-03-18 01:33 UTC, JVonderwell commented on holoclean/dataengine.py
> +                It returns a dataframe contains "columns_name_list" columns data
typo: dataframe that contains

2018-03-18 01:33 UTC, JVonderwell commented on holoclean/dataengine.py
> +                    The query that we want to have it results on the dataframe
wording: something as simple as 'query to execute' is probably fine here. it's a little wordy now.

2018-03-18 01:33 UTC, JVonderwell commented on holoclean/dataengine.py
> +            This is sql engine returns a sql engine
says sql engine twice. just 'returns a sql engine' is fine.

2018-03-18 01:33 UTC, JVonderwell commented on holoclean/dataengine.py
> +    This is the class that contains functionality
failing a few small pep8 tests in this file. please resolve.

2018-03-18 02:54 UTC, gmichalo submitted a review, later dismissed

2018-03-18 02:54 UTC, gmichalo commented on holoclean/dataengine.py
>          ----------
As we use :param to specify the parameters I do not think we need to have  also in the comments the word:
Parameters

2018-03-18 02:54 UTC, gmichalo commented on holoclean/dataengine.py
> +        :return: jdbc_url : String
The same comment as before, as we use :return to specify the return objects I do not think we need to have also in the comments the word:
 Returns

2018-03-18 03:22 UTC, ah89 commented on holoclean/dataengine.py
> +    This is the class that contains functionality
Fixed

2018-03-18 03:28 UTC, ah89 commented on holoclean/dataengine.py
> +        This method gets table general name and returns a spark dataframe
Fixed

2018-03-18 03:30 UTC, ah89 commented on holoclean/dataengine.py
> +        :param dataset: The data set object to access to the correct project
Fixed

2018-03-18 03:52 UTC, ah89 commented on holoclean/dataengine.py
> +                It returns a dataframe contains "columns_name_list" columns data
fixed

2018-03-18 03:52 UTC, ah89 commented on holoclean/dataengine.py
> +                    The query that we want to have it results on the dataframe
fixed

2018-03-18 03:54 UTC, ah89 commented on holoclean/dataengine.py
> +            This is sql engine returns a sql engine
Fixed

2018-03-18 03:56 UTC, ah89 commented on holoclean/dataset.py
> +        This method writes dataset id inside dataset_id.txt file and return that
Fixed

2018-03-18 04:09 UTC, j48zheng approved these changes

2018-03-18 21:18 UTC, j48zheng submitted a review, later dismissed

2018-03-18 21:39 UTC, JVonderwell submitted a review, later dismissed

2018-03-18 22:02 UTC, josmcg commented on holoclean/dataengine.py
> +           This parameter is the HoloClean object from the holoclean.py
"This parameter is [...]", is unnecessary.

2018-03-18 22:02 UTC, josmcg commented on holoclean/dataengine.py
> +    This is the class that contains functionality
This is the class that ...

2018-03-18 22:02 UTC, josmcg commented on holoclean/dataengine.py
> +                It returns a dataframe contains "columns_name_list" columns data
"It returns" is redundant

2018-03-18 22:02 UTC, josmcg commented on holoclean/dataengine.py
> +                It returns the results of sql_query in a dataframe
"It returns" is not needed

2018-03-18 22:02 UTC, josmcg commented on holoclean/dataengine.py
> +            This parameter is a dataset object used to store the ID
"This parameter is a" is redundant

2018-03-18 22:02 UTC, josmcg commented on holoclean/dataengine.py
> +        This method gets table general name and returns a spark dataframe as
"This method" is not needed

2018-03-18 22:02 UTC, josmcg commented on holoclean/dataengine.py
> +        This method returns MySQL database
"this method" is not needed.

2018-03-18 22:02 UTC, josmcg commented on holoclean/dataset.py
> +        This method writes dataset id inside dataset_id.txt file and return that
"This method" is not needed

2018-03-18 22:02 UTC, josmcg commented on holoclean/dataset.py
> +        This method returns detaset id as string
"This method" is not needed

2018-03-18 23:00 UTC, jw-mcgrath submitted a review, later dismissed

2018-03-18 23:01 UTC, gmichalo submitted a review, later dismissed

2018-03-19 01:22 UTC, gmichalo approved these changes

2018-03-19 02:21 UTC, thodrek approved these changes

2018-03-19 02:21 UTC, merged