Feature optimised Mysql error detector
HoloClean/HoloClean-Legacy-deprecated pull request #160
Opened 2018-03-20 23:22 UTC by ah89

2018-03-20 23:40 UTC, JVonderwell requested changes

2018-03-20 23:40 UTC, JVonderwell commented on holoclean/dataset.py
> +        'C_dk_temp',
make sure to add comments describing the tables in our giant list right below the names in this file

2018-03-20 23:40 UTC, JVonderwell commented on .travis2.yml
> +# Travis CI config for Holoclean, Weakly Supervised Data Cleaning
why two travis files?

2018-03-20 23:40 UTC, JVonderwell commented on holoclean/errordetection/mysql_dcerrordetector.py
> +    def _is_symetric(self, dc_name):
typo - symmetric

2018-03-20 23:40 UTC, JVonderwell commented on holoclean/errordetection/mysql_dcerrordetector.py
> +    def __init__(self, session):
please make sure tutorials and debug script are changed to match the new parameters. Tutorial_2 at least fails to run since it's using the DC, holo_obj, dataset model.

2018-03-20 23:40 UTC, JVonderwell commented on setup_mysql_user.sh
> +#echo "[i] Setting root new password..."
remove any commented code we're not using

2018-03-20 23:40 UTC, JVonderwell commented on test/sad.py
> +import unittest
file name? what does that mean?

2018-03-21 03:25 UTC, j48zheng commented on .travis2.yml
> +# Travis CI config for Holoclean, Weakly Supervised Data Cleaning
Removed

2018-03-21 03:25 UTC, j48zheng commented on holoclean/errordetection/mysql_dcerrordetector.py
> +    def _is_symetric(self, dc_name):
fixed

2018-03-21 03:33 UTC, j48zheng commented on test/sad.py
> +import unittest
removed the entire file, we don't need

2018-03-21 20:25 UTC, thodrek submitted a review, later dismissed
It looks ok to me but please verify that unit tests are going through.

2018-03-21 21:07 UTC, JVonderwell requested changes
failing init_featurizer, coccur_featurzer unit tests and overall_test.py

2018-03-22 02:18 UTC, JVonderwell approved these changes

2018-03-22 02:31 UTC, merged