Add sys import for exit, add some things to gitignore like .swp files
HoloClean/HoloClean-Legacy-deprecated pull request #241
Opened 2018-05-13 03:12 UTC by ankur-gos

Fix #223 
Added some gitignore things like swap files and tutorials/.ipynb_checkpoints

2018-05-13 14:03 UTC, JVonderwell submitted a review, later dismissed

2018-05-13 14:15 UTC, thodrek submitted a review, later dismissed

2018-05-13 16:19 UTC, gmichalo approved these changes

2018-05-13 16:45 UTC, gmichalo requested changes
Thanks for your input! Just a small requested change.Our policy for PR is to merge into dev, not into master. Please change the base-branch for this PR to dev

2018-05-13 21:35 UTC, ankur-gos commented
Thanks for the clarification! Changed to target dev.

2018-05-14 13:51 UTC, gmichalo submitted a review, later dismissed

2018-05-14 14:33 UTC, JVonderwell approved these changes

2018-05-14 14:34 UTC, merged