Describe project setup with _virtualenv_
HoloClean/HoloClean-Legacy-deprecated pull request #246
Opened 2018-05-13 11:33 UTC by CodeLionX

see #245

2018-05-13 14:14 UTC, JVonderwell submitted a review, later dismissed

2018-05-13 16:47 UTC, gmichalo requested changes
Thanks for your input! Just a small requested change.Our policy for PR is to merge into dev, not into master. Please change the base-branch for this PR to dev

2018-05-13 16:56 UTC, gmichalo submitted a review, later dismissed

2018-05-14 14:37 UTC, JVonderwell approved these changes

2018-05-14 14:37 UTC, merged