Holoclean v.0.1.1
HoloClean/HoloClean-Legacy-deprecated pull request #252
Opened 2018-05-14 21:34 UTC by gmichalo

In the pull request from dev to master we will add:
Features:
  1) k-inference values
  2) unittests for pruning and initfeaturizer
  3) adding reset_database() method that deletes all the tables from the database
  4) updating reader to check for columns with values with more than 250 characters
  prompts user to remove these columns 
  5) updating parser_interface to check if we have more than one attribute per predicate
  raise exception early to prevent errors in error detection

Cleanup/Bug Fixes:
  1) Removing unused variables from softmax.py
  2) Fixing method remove_denial_constraint in holoclean.py
  3) Removing __ind collumn from the final table
  4) Updating the python_requirement.txt
  5) Updating README.md

2018-05-15 02:34 UTC, thodrek requested changes
Everything looks good to me apart from the evaluation print outs

"The MAP recall is : 0.978378378378 out of 185"

We should round to three decimals (%.3f) and also you are missing something " what 0.9 out of 185" even mean. Please fix that.

2018-05-15 02:34 UTC, thodrek commented on python-package-requirement.txt
> +
why an empty + ?

2018-05-15 12:59 UTC, thodrek commented
Oh another thing that needs to be fixed. When I run with different FDs I get a different number of items (i.e., not 185 in hospital). This is wrong. The set cells we evaluate on should be those that have a different value in groundtruth vs init.

2018-05-21 21:29 UTC, jw-mcgrath reviewed
Great work guys! Only thing I noticed was this, but all the code looks good.

2018-05-21 21:29 UTC, josmcg commented on holoclean/holoclean.py
> +        self.holo_env.logger.info('Added new error detection')
"Added new error detector"

2018-05-21 21:29 UTC, jw-mcgrath approved these changes

2018-05-23 14:18 UTC, thodrek approved these changes

2018-05-23 14:19 UTC, merged