#44 first draft
HoloClean/HoloClean-Legacy-deprecated pull request #63
Opened 2018-03-03 00:04 UTC by josmcg

2018-03-03 21:23 UTC, josmcg commented
Need to add template for error detection modules

2018-03-04 19:59 UTC, j48zheng requested changes
Move the table of Denial Constraint Operators up since they are used earlier in the tutorial.
As an additional comment: should we include the non-symmetrical operators in the table for this release, since holoclean does not support it properlly at the moment.

2018-03-05 00:01 UTC, josmcg commented
Hey all, I have made some changes to make sure everything works correctly, and made some slight changes to wording. @thodrek, could you comment on the order in which I introduce the operators?

2018-03-05 00:25 UTC, thodrek requested changes

2018-03-05 00:25 UTC, thodrek commented on tutorial/Denial Constraints.ipynb
> +    "HoloClean's goal is to clean your data, and the system is driven by a description of what clean data *should not* be like. These are expressed in the form of a Denial Constraint, which is simila
"what clean data should not be like. " -> "what clean data should look like" we are asking people to specify invariances that hold. "which is similar to a functional dependency" -> add a hyperlink to the wikipedia entry of functional dependency

2018-03-05 00:25 UTC, thodrek commented on tutorial/Denial Constraints.ipynb
> +    "|Chicago|60607|\n",
Is Chicago present in the hospital dataset? I don't think so. change it to contain examples from the actual dataset. Even better load and query the dataset while you point them to the loading tutorial.

2018-03-05 00:25 UTC, thodrek commented on tutorial/Denial Constraints.ipynb
> +    "Denial Constraints are just one of HoloClean's error detectors that it uses for learning, if you'd like to write your own check out our error detectors tutorial. If you want to learn about the n
Add a hyperlink to the repairs tutorial.

2018-03-05 00:27 UTC, gmichalo submitted a review, later dismissed
When I run the notebook I got this error:
DCFormatException: Duplicate Denial Constraint

In the line
session.add_denial_constraint()
we need to add a dc that we do not already have

2018-03-05 01:28 UTC, josmcg commented
I fixed these changes, please review again.

2018-03-05 03:10 UTC, gmichalo reviewed
I think it is better that the first cell in the notebook should be the title and the description and afterwards we can write the loading of the holoclean session with a small description in three cells : 
cell 1)Firstly we create a holoclean session and we ingest the Hospital dataset. 
cell 2) The code that we have
cell 3) The data has the following fields: ...

2018-03-05 17:10 UTC, thodrek approved these changes
Looks good to me now.

2018-03-05 17:12 UTC, j48zheng approved these changes

2018-03-05 17:20 UTC, gmichalo approved these changes

2018-03-05 18:06 UTC, merged