Pytorch clean
HoloClean/HoloClean-Legacy-deprecated pull request #86
Opened 2018-03-06 04:55 UTC by JVonderwell

2018-03-06 04:57 UTC, gmichalo submitted a review, later dismissed

2018-03-06 19:10 UTC, thodrek requested changes
Comments on main readme:
1) There is no getting started instructions and pointers to the tutorials in the main readme
2) The blogpost should point to my webpage not dawn and also remove the word "recent" before the blogpost link
Other comments:
Are the .ipynb_checkpoints folder/files needed in the tutorial director? I don't think so do please remove.

2018-03-07 13:44 UTC, thodrek submitted a review, later dismissed

2018-03-07 19:10 UTC, jw-mcgrath submitted a review, later dismissed

2018-03-07 19:52 UTC, jw-mcgrath approved these changes

2018-03-07 19:52 UTC, merged